// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_grpc.proto
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MyNumber {
    #[prost(int32, tag = "1")]
    pub value: i32,
}