use std::fs;
use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // proto 파일 컴파일
    tonic_build::configure()
        .build_server(true)
        .build_client(true)
        .out_dir("gen")
        .compile(&["proto/hello_grpc.proto"], &["proto/"])?;

    // gen/hello_grpc.rs 파일을 읽어서 분리
    let generated_file = Path::new("gen/hello_grpc.rs");
    
    if generated_file.exists() {
        let content = fs::read_to_string(generated_file)?;
        
        // MyNumber 메시지 부분 추출 (처음부터 "Generated client" 또는 "/// Generated client" 전까지)
        let client_start = content
            .find("/// Generated client")
            .or_else(|| content.find("#[doc = r\" Generated client"))
            .or_else(|| content.find("pub mod my_service_client"));
        
        if let Some(start) = client_start {
            let msg_content = &content[..start];
            
            // hello_grpc_pb2.rs 생성
            fs::write(
                "src/hello_grpc_pb2.rs",
                format!(
                    "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n// source: hello_grpc.proto\n{}",
                    msg_content.trim()
                )
            )?;
            
            // 클라이언트/서버 부분 추출
            let grpc_content = &content[start..];
            
            // hello_grpc_pb2_grpc.rs 생성
            fs::write(
                "src/hello_grpc_pb2_grpc.rs",
                format!(
                    "// Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!\nuse super::hello_grpc_pb2::MyNumber;\n\n{}",
                    grpc_content
                )
            )?;
        }
    }

    Ok(())
}
